version: '2.1'

services:
  photo-carousel:
    image: blbst123/photo-carousel
    depends_on:
      database: 
        condition: service_healthy
    ports: 
      - '3003:3003'

  database:
    image: blbst123/photo-carousel-database
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'photo_gallery'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10